//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GifGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update
    {
        public int Id { get; set; }
        public int UpdateId { get; set; }
        public int UpdateType { get; set; }
        public string SerializedUpdate { get; set; }
        public System.DateTime CreationDatetime { get; set; }
        public int Status { get; set; }
        public System.DateTime ModifiedDatetime { get; set; }
    }
}
