//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GifGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public int CardPosition { get; set; }
        public int MemId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public System.DateTime ExaminationDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string UserId { get; set; }
        public int Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Mem Mem { get; set; }
    }
}
