//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GifGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int Id { get; set; }
        public int MemId { get; set; }
        public byte[] MediumContent { get; set; }
        public string ContentType { get; set; }
    
        public virtual Mem Mem { get; set; }
    }
}
